language: python
cache: pip
python:
  - 3.6
  - 3.6-dev
  # - 3.7-dev
  # - nightly

install:
  - python3 -m pip install -U -r dev-requirements.txt
script:
  - python3 -m pytest tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
